site_name: Unparallel Weather Station
site_url: http://10.0.1.55:8000/dev-corner/
site_description: Project documentation about the Unparallel Weather Station
site_author: Unparallel Innovation, Lda
site_favicon: img/weather_station_favicon2x.png
# Local
#site_dir: site
# Server
site_dir: /var/www/html/dev-corner

repo_url: https://www.iot-catalogue.com/search/component/60704f126dc1142086fa54f6

pages:
- Home: index.md
- Assemble your Weather Station:
    - Introduction: Assemble/Introduction.md
    - Have the 3d print available: Assemble/1_Have-the-3d-print-available.md
    - Prepare AM2315 sensor: Assemble/2_Prepare-AM2315-sensor.md
    - Adding AM2315 and Antenna to enclosure: Assemble/3_Adding_AM2315_and_Antenna_to_enclosure.md
    - Prepare Weather Meter Kit SEN-15901: Assemble/4_Prepare_Weather_Meter_Kit_SEN-15901.md
    - Prepare the panel solar: Assemble/5_Prepare_the_panel_solar.md
    - Adding cables to enclosure: Assemble/6_Adding_cables_to_enclosure.md
    - Attaching clamp to the enclosure and checking battery connector: Assemble/7_Attaching_clamp_to_the_enclosure_and_checking_battery_connector.md
    - Adding LoPy4 to the PCB: Assemble/8_Adding_LoPy4_to_the_PCB.md
    - Identifying sensors connectors and make connections: Assemble/9_Identifying_sensors_connectors_and_make_connections.md
    - Closing enclosure: Assemble/10_Closing_enclosure.md
    - Adding cord rubber (optional): Assemble/11_Adding_cord_rubber_(optional).md
    - Adding solar panel support to the enclosure: Assemble/12_Adding_solar_panel_support_to_the_enclosure.md
    - Adding claw to the enclosure: Assemble/13_Adding_claw_to_the_enclosure.md
    - Start receiving measures: Assemble/14_Start_receiving_measures.md
- Board:
    - Board Ports: BoardSpecs/Board_Specs.md

# - NewSection
    #- newPage: newSection/newPage.md
# - newSinlePage: newSinlePage.md
extra_css: [css/styles.css]

theme:
    name: readthedocs
    custom_dir: custom_theme

markdown_extensions:
    - toc:
        permalink: true

copyright: Copyright &copy; 2021 <a href="https://www.unparallel.pt">UNPARALLEL Innovation, Lda</a>.
google_analytics: ['UA-74601518-1', 'http://giv-oct.uni-muenster.de/dev-corner/']
